return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.rust" },
  { import = "astrocommunity.pack.cmake" },
  { import = "astrocommunity.pack.python" },
  { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.colorscheme.tokyonight", enable=true },
  { import = "astrocommunity.completion.copilot-lua-cmp" },
  { import = "astrocommunity.diagnostics.trouble-nvim" },
  { import = "astrocommunity.editing-support.neogen" },
  { import = "astrocommunity.editing-support.todo-comments-nvim" },
  { import = "astrocommunity.editing-support.treej" },
  { import = "astrocommunity.file-explorer.oil-nvim" },
  { import = "astrocommunity.media.pets-nvim" },
  { import = "astrocommunity.note-taking.neorg" },
  { import = "astrocommunity.project.nvim-spectre" },
  { import = "astrocommunity.test.neotest" },
}
